services:
  app:
    container_name: release-agent-app
    image: ${DOCKER_IMAGE:-release-agent}
    build:
      context: .
      target: "service"
    ports:
      - 127.0.0.1:${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    environment:
      APP_SERVICE: app
      DB_HOST: db
      REDIS_HOST: redis
      CH_HOST: clickhouse
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy

  db:
    container_name: release-agent-db
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - ${PWD}/.data/postgres:/var/lib/postgresql/data/pgdata

  redis:
    container_name: release-agent-redis
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - ${PWD}/.data/redis:/data

  clickhouse:
    container_name: release-agent-clickhouse
    image: clickhouse:25.9
    env_file:
      - .env
    environment:
      CLICKHOUSE_DB: ${CH_DATABASE}
      CLICKHOUSE_USER: ${CH_USER}
      CLICKHOUSE_PASSWORD: ${CH_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - ${PWD}/.data/clickhouse:/var/lib/clickhouse
    ports:
      - "127.0.0.1:8123:8123"

  test:
    container_name: release-agent-test
    image: release-agent:test
    env_file:
      - .env
    build:
      context: .
      target: tests
      args:
        DEV_DEPS: true
    environment:
      APP_SERVICE: test
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy

  lint:
    container_name: release-agent-lint
    image: release-agent:test
    env_file:
      - .env
    build:
      context: .
      target: tests
      args:
        DEV_DEPS: true
    environment:
      APP_SERVICE: lint
