name: Test
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare .env file
        run: |
          cp .env.template .env
          echo "DB_PASSWORD=postgres" >> .env
          echo "APP_SECRET_KEY=test" >> .env
          echo "ADMIN_PASSWORD=test" >> .env
          echo "CH_PASSWORD=test" >> .env
          env >> .env

      - name: Build images
        run: |
          docker compose build test

      - name: Run linters
        run: docker compose up --exit-code-from lint lint

      - name: Run tests
        run: docker compose up --exit-code-from test test
